# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

  platform :ios, min_ios_version_supported
  prepare_react_native_project!

$RNFirebaseAsStaticFramework = true
use_frameworks! :linkage => :static

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
if flipper_config == FlipperConfiguration.enabled
  flipper_config = FlipperConfiguration.disabled # Disabling Flipper due to incompatibility with use_frameworks!
end

target 'epsikiyatri' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled], 
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => flipper_config, # Adjusted based on use_frameworks! compatibility
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'epsikiyatriTests' do
    inherit! :complete
    # Pods for testing can be added here
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
